title: "Lokesh Kumar Jayswal"
email: lokeshkjayswal999@gmail.com
description: "AI Engineer & Backend Developer building modular AI systems and production-oriented backend architectures."
baseurl: ""
url: "https://decoder76.github.io"
github_username: decoder76
linkedin_username: lokesh-kumar-j-792389195
repository: "Decoder76/decoder76.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /projects/:slug/
  knowledge:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
